- id: gettext
  name: gettext
  description: 'Generate the .pot file for the specified sources'
  entry: sphinx-build -b gettext
  language: bash
  args: ["docs/source", "docs/build/gettext"]
  minimum_pre_commit_version: 2.9.2
  additional_dependencies: ["sphinx"]
- id: intl
  name: intl
  description: "Generate the .po files from the specified gettext source to locale dir"
  entry: sphinx-intl update -p
  language: bash
  args: ["docs/build/gettext", "--locale-dir=docs/source/_locale"]
  minimum_pre_commit_version: 2.9.2