language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
matrix:
  exclude:
    - python: "3.5"
    - python: "3.4"
    - python: "3.3"
    - python: "2.7"
    - python: "2.6"
  include:
    - python: "3.5"
      env: TOXENV=flake8
    - python: "3.5"
      env: TOXENV=sdist
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.3"
      env: TOXENV=py33
    - python: "2.7"
      env: TOXENV=py27
    - python: "2.6"
      env: TOXENV=py26
install:
  - pip install -r requirements-testing.txt
cache: pip
script:
  - tox
